name: android_map_directory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  google_fonts: ^6.2.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.1


  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_musra.png